pipeline {
    agent any
    tools {
        maven 'MAVEN'


    }
    stages {
        stage ('initialize') {
            steps {
                echo "PATH = ${M2_HOME}/bin:${PATH}"
                echo "M2_HOME = /opt/maven"
            }
        }
    

        stage ('Build') {
            steps {
                echo 'This is my first pipeline'
            }
        }
    }
}